site_name: "橙世闲游"

nav: # 导航栏菜单结构，层级与目录结构对应
    - 前言: index.md
    - Python 预备知识:
          - 1 Python程序基本结构: basic/01_Python程序基本结构.md
          - 2 基础语法与变量: basic/02_基础语法与变量.md
          - 3 核心数据结构: basic/03_核心数据结构.md
          - 4 运算符与表达式: basic/04_运算符与表达式.md
          - 5 程序控制流: basic/05_程序控制流.md
          - 6 函数: basic/06_函数.md
          - 7 文件操作: basic/07_文件操作.md
          - 8 错误与异常处理: basic/08_错误与异常处理.md
          - 9 面向对象编程基础: basic/09_面向对象编程基础.md
    - Python 进阶修炼:
          - 1 推导式: advanced/01_推导式.md
          - 2 迭代器与生成器: advanced/02_迭代器与生成器.md
          - 3 上下文管理器: advanced/03_上下文管理器.md
          - 4 装饰器: advanced/04_装饰器.md
          - 5 数据结构: advanced/05_数据结构.md
          - 6 模块与包: advanced/06_模块与包.md
          - 7 进阶输入输出: advanced/07_输入输出.md
          - 8 命名空间与作用域: advanced/08_命名空间与作用域.md
          - 9 类型注解: advanced/09_类型注解.md
          - 10 标准库概览: advanced/10_标准库概览.md
          - 11 异步IO: advanced/11_异步IO.md
    - 算法基础:
          - 1 算法概述: algo/01_算法概述.md
          - 2 模拟与枚举: algo/02_模拟与枚举.md
          - 3 递归: algo/03_递归.md
          - 4 分治: algo/04_分治.md
          - 5 二分查找: algo/05_二分查找.md
          - 6 动态规划: algo/06_动态规划.md
          - 7 背包问题: algo/07_背包问题.md
          - 8 贪心算法: algo/08_贪心算法.md
          - 9 搜索算法: algo/09_搜索算法.md
          - 10 图论基础: algo/10_图论基础.md
    - 算法实战:
          - 1 Hot100(上): leetcode/01_Hot100.md
          - 2 Hot100(中): leetcode/02_Hot100.md
          - 3 Hot100(下): leetcode/03_Hot100.md
          - 4 面试经典150(上): leetcode/04_面试经典150.md
          - 7 Hot100二刷: leetcode/07_Hot100.md
          - 8 算法手撕: leetcode/08_算法手撕.md
    - Agent:
          - 1 Hello-Agents: agent/01_Hello-Agents.md
    - 数据科学:
          - 1 生命周期: data_science/01_生命周期.md
          - 2 矩形数据: data_science/02_矩形数据.md
          - 3 SQL与关系数据: data_science/03_SQL.md
          - 4 文件处理: data_science/04_文件处理.md
          - 5 数据清洗: data_science/05_数据清洗.md
          - 6 数据分析: data_science/06_数据分析.md
          - 7 数据可视化: data_science/07_数据可视化.md
          - 8 案例研究: data_science/08_案例研究.md
          - 9 文本数据: data_science/09_文本数据.md
          - 10 数据交换: data_science/10_数据交换.md
          - 11 线性模型: data_science/11_线性模型.md
          - 12 模型选择: data_science/12_模型选择.md
          - 13 推理与预测理论: data_science/13_推理与预测理论.md
          - 14 案例研究: data_science/14_案例研究.md
          - 15 分类: data_science/15_分类.md
          - 16 数值优化: data_science/16_数值优化.md
          - 17 案例研究: data_science/17_案例研究.md
    - 爆肝杰哥深度学习:
          - Python深度学习: jie_course/Python深度学习.md
          - Numpy: jie_course/numpy.md
          - Matplotlib: jie_course/matplotlib.md
          - Pandas: jie_course/pandas.md
          - DNN: jie_course/DNN.md
          - CNN: jie_course/CNN.md
    - Pytorch:
          - 小土堆Pytorch: pytorch/小土堆Pytorch.md
          - AI问答: pytorch/AI问答.md
    - 吴恩达机器学习:
          - 0 AI问答: wu_course/00_AI问答.md
          - 1 机器学习基础: wu_course/01_机器学习基础.md
    - 李沐动手学深度学习(书):
          - 1 动手学深度学习: limu_course/01_动手学深度学习.md
    - 自然语言处理:
          - 1 软微自然语言处理: nlp/01_自然语言处理.md
    - 后训练:
          - 1 后训练概述: post_training/01_后训练概述.md
          - 2 软微后训练: post_training/02_软微后训练.md
          - 3 AI问答: post_training/03_AI问答.md
          - 4 踩坑日记: post_training/04_踩坑日记.md
          - 5 Huggingface trl: post_training/05_trl.md
          - 6 rlhfbook: post_training/06_rlhfbook.md
    - 强化学习:
          - 1 动手学强化学习: rl/01_动手学强化学习.md
    - AI infra:
          - 1 入门路线: ai_infra/01_入门路线.md
    - 面经:
          - 1 面经流水账: interview/面经流水账.md
          - 2 可投递公司汇总: interview/可投递公司汇总.md
          - 3 TeleAI 大模型算法实习面经: interview/01.md
          - 4 粽子的面经: interview/02.md
          - 5 正在思考的超人强整理的手撕算法: interview/03.md
          - 6 京东大模型算法实习面经: interview/04.md
          - 7 淘天大模型算法面经: interview/05.md
          - 8 字节大模型算法面经: interview/06.md
          - 9 美团大模型算法面经: interview/07.md
          - 10 腾讯大模型算法面经: interview/08.md
          - 11 阿里高德大模型算法面经: interview/09.md
          - 12 百度大模型算法面经: interview/10.md
          - 13 小红书大模型算法面经: interview/11.md
          - 14 阿里国际大模型算法面经: interview/12.md
          - 15 其他大模型算法面经: interview/13.md
    - 经验贴参考:
        - 1 大模型算法岗，3个项目走上人生，癫疯😎: references/01.md
        - 2 如何找到第一份大厂算法岗日常实习: references/02.md
        - 3 如何找到第一段搜广推实习: references/03.md
        - 4 非科班转大模型快速学习路线: references/04.md
        - 5 我的大模型零基础学习路线(已实习): references/05.md
        - 6 辰屿九秋的大模型开发和算法学习路线: references/06.md
        - 7 小白的SFT、RL完整学习路线: references/07.md
        - 8 粽子的如何找到第一份大模型实习: references/08.md
        - 9 考研电子宠物的转码经验贴: references/09.md
        - 10 叶云的转大模型算法最快路线: references/10.md
        - 11 CherieCame的八股框架: references/11.md
        - 12 两万人看过的“混进”算法岗后续: references/12.md
        - 13 AI问答: references/13.md
    - 八股:
        - 1 minimind: bagu/01_github.md
        - 2 技术报告: bagu/02_技术报告.md
        - 3 qwen回答: bagu/03_qwen回答.md
        - 4 ds回答: bagu/04_ds回答.md
    - 项目:
        - 1 电商客服: project/电商客服.md
    - 实用工具:
          - 1 Git与版本控制: tools/01_Git与版本控制.md
          - 2 Markdown: tools/02_Markdown.md
          - 3 Vibe Coding: tools/03_Vibe_Coding.md
          - 4 LeetCode: tools/04_LeetCode.md
          - 5 coze: tools/05_coze.md
          - 6 n8n: tools/06_n8n.md
          - 7 PPT: tools/07_PPT.md

theme:
    name: material #主题
    language: zh #语言

markdown_extensions:
    - admonition
    - pymdownx.highlight
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.tilde

extra_javascript:
    - javascripts/config.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search
